In [55]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [56]:
df = pd.read_csv("C:/Users/lenovo/Downloads/ShopSphere-Customer-Intelligence/data/raw/Superstore.csv", encoding="latin1")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [57]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 9994
Columns : 21

In [58]:
df.columns
df.dtypes
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [59]:
df.describe(include="object")
df.isnull().sum()
df.duplicated().sum()
for col in df.columns:
    print(f"{col}: {df[col].nunique()}")

Row ID: 9994
Order ID: 5009
Order Date: 1237
Ship Date: 1334
Ship Mode: 4
Customer ID: 793
Customer Name: 793
Segment: 3
Country: 1
City: 531
State: 49
Postal Code: 631
Region: 4
Product ID: 1862
Category: 3
Sub-Category: 17
Product Name: 1850
Sales: 5825
Quantity: 14
Discount: 12
Profit: 7287

C:\Users\lenovo\AppData\Local\Temp\ipykernel_6748\2122626260.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

In [60]:
numerical = df.select_dtypes(include=np.number).columns

categorical = df.select_dtypes(exclude=np.number).columns

print("Numerical Columns")
print(numerical)

print()

print("Categorical Columns")
print(categorical)

Numerical Columns
Index(['Row ID', 'Postal Code', 'Sales', 'Quantity', 'Discount', 'Profit'], dtype='str')

Categorical Columns
Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Region',
       'Product ID', 'Category', 'Sub-Category', 'Product Name'],
      dtype='str')

In [61]:
df.memory_usage(deep=True)
print(df.memory_usage(deep=True).sum() / 1024**2, "MB")

9.221195220947266 MB

In [62]:
profile = pd.DataFrame({
    "Data Type": df.dtypes,
    "Missing Values": df.isnull().sum(),
    "Unique Values": df.nunique()
})

profile

              Data Type  Missing Values  Unique Values
Row ID            int64               0           9994
Order ID            str               0           5009
Order Date          str               0           1237
Ship Date           str               0           1334
Ship Mode           str               0              4
Customer ID         str               0            793
Customer Name       str               0            793
Segment             str               0              3
Country             str               0              1
City                str               0            531
State               str               0             49
Postal Code       int64               0            631
Region              str               0              4
Product ID          str               0           1862
Category            str               0              3
Sub-Category        str               0             17
Product Name        str               0           1850
Sales           float64               0           5825
Quantity          int64               0             14
Discount        float64               0             12
Profit          float64               0           7287

In [63]:
clean_df = df.copy()

In [64]:
clean_df["Order Date"] = pd.to_datetime(clean_df["Order Date"])

clean_df["Ship Date"] = pd.to_datetime(clean_df["Ship Date"])
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(3), str(13)
memory usage: 1.6 MB

In [65]:
clean_df[clean_df["Sales"] < 0]
clean_df[clean_df["Profit"] < 0]
clean_df["Discount"].describe()

count    9994.000000
mean        0.156203
std         0.206452
min         0.000000
25%         0.000000
50%         0.200000
75%         0.200000
max         0.800000
Name: Discount, dtype: float64

In [66]:
text_columns = clean_df.select_dtypes(include="object").columns

for col in text_columns:
    clean_df[col] = clean_df[col].str.strip()

C:\Users\lenovo\AppData\Local\Temp\ipykernel_6748\4160171661.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = clean_df.select_dtypes(include="object").columns

In [67]:
clean_df.duplicated().sum()

np.int64(0)

In [68]:
clean_df["Delivery Days"] = (
    clean_df["Ship Date"] - clean_df["Order Date"]
).dt.days

In [69]:
clean_df["Order Year"] = clean_df["Order Date"].dt.year

In [70]:
clean_df["Order Month"] = clean_df["Order Date"].dt.month_name()

In [71]:
clean_df["Month Number"] = clean_df["Order Date"].dt.month

In [72]:
clean_df["Quarter"] = clean_df["Order Date"].dt.quarter

In [73]:
clean_df["Weekday"] = clean_df["Order Date"].dt.day_name()

In [74]:
clean_df["Weekend Order"] = clean_df["Weekday"].map(
    {True: "Weekend", False: "Weekday"}
)

In [75]:
clean_df["Profit Margin %"] = (
    clean_df["Profit"] / clean_df["Sales"]
) * 100

In [76]:
clean_df["Sales Bucket"] = pd.cut(
    clean_df["Sales"],
    bins=[0,100,500,1000,5000,25000],
    labels=[
        "Very Low",
        "Low",
        "Medium",
        "High",
        "Very High"
    ]
)

In [77]:
clean_df["Discount Category"] = pd.cut(
    clean_df["Discount"],
    bins=[-0.01,0,0.2,0.5,1],
    labels=[
        "No Discount",
        "Low",
        "Medium",
        "High"
    ]
)

In [78]:
clean_df.to_csv(
    "C:/Users/lenovo/Downloads/ShopSphere-Customer-Intelligence/data/cleaned/superstore_cleaned.csv",
    index=False
)